### ISSUE TITLE
Jasmine 2.2.1

### ISSUE THREAD

**Issue by victorwpbastos** [bitovi/funcunit#100]
When I try to use FuncUnit with the Jasmine 2.2.1:

![image](https://cloud.githubusercontent.com/assets/1017515/6926006/d1aee5fe-d7b9-11e4-9c64-01e921a7295a.png)

Any idea?

**Comment by victorwpbastos** [comment]
In fact, any Jasmine 2.x gives me that error.

**Comment by justinbmeyer** [comment]
Thanks for reporting!

**Comment by alexisabril** [comment]
FuncUnit doesn't have a driver yet for Jasmine 2.x(but we should and it would be almost identical to the mocha adapter)

**Comment by israfil334** [comment]
waitsFor does the same thing. Jasmine 2.0 overhauled Async goodies. Now we get afterAll(), beforeAll() and async it()

**Comment by php-max** [comment]
What does it mean? workable or have a work arround solution?

**Comment by alexisabril** [comment]
@php-max We actually just created a pre-release branch for 3.1.0 that does have support for 2.x: https://github.com/bitovi/funcunit/commits/3.1.0-pre

We should have a tagged pre-release here in the next week as we polish up a few details.

**Comment by mickmcgrath13** [comment]
Closing because we're supporting Jasmine > 2.5, now.  Please re-open if there are still issues.

https://github.com/bitovi/funcunit/blob/master/package.json#L57
