### ISSUE TITLE
Readme not showing up on npm

### ISSUE THREAD

**Issue by matthewp** [bitovi/funcunit#103]
https://www.npmjs.com/package/funcunit

**Comment by m-mujica** [comment]
@matthewp I can see the readme there, there is only one issue

![screen shot 2016-03-23 at 10 46 09](https://cloud.githubusercontent.com/assets/724877/13987047/7c754fd4-f0e4-11e5-9dff-67004327839d.png)

that's some documentjs stuff, I guess we can just move that into its own markdown file and that will fix it. What do you think? should we close this?

**Comment by matthewp** [comment]
yeah close it, wasn't showing up at all before
