### ISSUE TITLE
Home page bithub links are broken

### ISSUE THREAD

**Issue by marshallswain** [bitovi/funcunit#109]
### These links

![funcunit-bithub-links](https://cloud.githubusercontent.com/assets/128857/7604365/c603a4f4-f8fe-11e4-8797-48881e62926b.png)
### go here:

![bithub-404](https://cloud.githubusercontent.com/assets/128857/7604370/e555b28e-f8fe-11e4-92b6-162bf9c9b90d.png)

**Comment by mickmcgrath13** [comment]
Need to add this back:
https://github.com/bitovi/funcunit/blob/master/site/app/app.js#L53

**Comment by mickmcgrath13** [comment]
Actually, we're removing bithub from FuncUnit :)

**Comment by mickmcgrath13** [comment]
This:
![image](https://cloud.githubusercontent.com/assets/1030325/19972026/d60c2088-a1ae-11e6-8a26-f0e96427fc43.png)

or This:
![image](https://cloud.githubusercontent.com/assets/1030325/19972061/f4a6c2b4-a1ae-11e6-886f-75ba32384874.png)

**Comment by mickmcgrath13** [comment]
Going with "or This:"
![image](https://cloud.githubusercontent.com/assets/1030325/19974742/80e9e74e-a1b7-11e6-88ad-12c596a1646c.png)
