### ISSUE TITLE
funcunit.com pages have no title

### ISSUE THREAD

**Issue by daffl** [bitovi/funcunit#121]
All titles at funcunit.com are empty

**Comment by marshallswain** [comment]
I only see a problem with the API home page.  It's set up that way because it's being pulled from the README.md.

**Comment by marshallswain** [comment]
<img width="984" alt="screen shot 2015-07-08 at 11 15 49 am" src="https://cloud.githubusercontent.com/assets/128857/8576968/c5d8eaee-2562-11e5-9620-597fc892e32a.png">
<img width="980" alt="screen shot 2015-07-08 at 11 15 57 am" src="https://cloud.githubusercontent.com/assets/128857/8576969/c5dc8c80-2562-11e5-8a92-97f188a7dc78.png">

**Comment by daffl** [comment]
I meant the actual page `<title>` tag:

![screen shot 2015-07-08 at 11 20 18 am](https://cloud.githubusercontent.com/assets/338316/8577067/86073d7a-2563-11e5-888f-38c6f6062354.png)

**Comment by marshallswain** [comment]
oh.  THAT title.  :)
