### ISSUE TITLE
Sometimes click() method gives for Anchor tag

### ISSUE THREAD

**Issue by santhoshranjan** [bitovi/funcunit#122]
Hi ,

Im having muliple anchor tags with same classes  in HTML, But each anchor tag exisit in some unique Div. Can you please tell me how to click the anchor tag by using FuncUnit

**Comment by alexisabril** [comment]
Hey @santhoshranjan, FuncUnit uses jQuery behind the scenes to select elements on the page.

So, F('a.foo') would be identical to $('a.foo'), which potentially selects multiple anchor tags. You'll need some type of unique selector to find the anchor you're trying to click on.

F('a.foo:first').click() for example would click the first anchor found with the "foo" class.

**Comment by santhoshranjan** [comment]
Hi Alex,
Thank you very much for your quick response, As per your suggestion i have implemented but still its not trigerring the next button.

I'm pasting my anchor tag code here:

<a  class="next roundButton orangeGrad floatRight" href="#">											
<span class="downarrow">次へ</span></a>

I will be having similar the 4 anchor tag  in my html. and I need to respective logic on click of achor tag.


I tried with the following code
F('a.next:first').click(); but its not working. Can you help me in this.
