### ISSUE TITLE
Better error message when F.open() is blocked by popup blocker

### ISSUE THREAD

**Issue by bittuamar** [bitovi/funcunit#132]
There needs to be a better error message thrown/displayed when F.open() is blocked by popup blocker. The error currently says Uncaught TypeError: Cannot read property '___FUNCUNIT_OPENED' of undefined. 
It's not enough to indicate the probable issue.

Thanks

**Comment by marshallswain** [comment]
This is fixed in #119.

**Comment by mickmcgrath13** [comment]
Thanks @marshallswain.  Closing
