### ISSUE TITLE
I can't get funcunit to run

### ISSUE THREAD

**Issue by RALifeCoach** [bitovi/funcunit#133]
I am searching for a basic example of running funcunit from the command line. In general I am told to type: ./js funcunit/open/... link to html. I don't have a command ./js or js. The other option is to run node node ... when I do node starts, but I am told node does not exist. That is true, there is no file 'node' in the current directory. Some posts suggest going to the funcunit folder. The file does not exist there either.

I am running on a MAC. Please help me! I am using funcunit 3.0.0.

Thanks

**Comment by matthewp** [comment]
@RALifeCoach FuncUnit doesn't run from the command line. It might have a long time ago, but doesn't any more. You probably want to try out Testee which can run your FuncUnit tests from the command line. https://github.com/bitovi/testee

**Comment by RALifeCoach** [comment]
Thanks Matthew. I downloaded testee and phantomjs and ran my test. It starts, puts out a blank line, a couple of spaces and stops. No errors, no warnings, just stops. After 2 minutes it times out. Any suggestions? My HTML is quite long, but it ends with:

<script src="/node_modules/jasmine-core/lib/jasmine-core.js"></script>
<script src="/js/vendor/funcunit.js"></script>
<script src="/tests/full/modules/page-tournament/tournament-banner/pgatour-tournament-banner-test.js"></script>
<script type="text/javascript">
    var jasmineEnv = jasmine.getEnv();
    var htmlReporter = new jasmine.HtmlReporter();
    jasmineEnv.addReporter(htmlReporter);
    jasmineEnv.specFilter = function(spec) {
        return htmlReporter.specFilter(spec);
    };
    jasmineEnv.execute();
</script>

The test file is:
describe("tests.full.modules.page-tournament.tournament-banner.pgatour-tournament-banner-test", function () {
    it('kajhkashkjh', function (done) {
        console.log('here');
        F('.s-tour').click(function () {
            expect(F('.s-tour').parent().hasClass('active')).toBeTrue();
            F('.h-tour').click(function () {
                expect(F('.h-tour').parent().hasClass('active')).toBeTrue();
                done();
            });
        });
    });

    it('kajhkashkjh', function () {
        F('.s-tour');
        var i = 16;
        var module = pgatour.videoPlayer;
        expect(module).toEqual(jasmine.any(Function));
    });
});

**Comment by daffl** [comment]
@RALifeCoach PhantomJS can't open popup windows so the test will never start. I think @alexisabril has a setup for using iFrames to make that work. First I would test if running from the command line works with other browser like Firefox though.

**Comment by RALifeCoach** [comment]
@daffl Thanks for that. I now have it working on Firefox. @alexisabril can you please assist with PhantomJS?

**Comment by matthewp** [comment]
Is this still an issue for you?

**Comment by RALifeCoach** [comment]
No it is no longer an issue.
