### ISSUE TITLE
Touch Support

### ISSUE THREAD

**Issue by victor-xiong** [bitovi/funcunit#135]
I'm using FuncUnit a lot for JS testing, and wondering if there is any plan for FuncUnit to provide touch events API such as tap, long hold, pinch.

**Comment by matthewp** [comment]
It's something we've wanted for a long time, however probably will need someone in the community to take on development.

**Comment by binodpanta** [comment]
I am interested to explore this as long as we can be clear about what can do next in touch and funcunit. An example test page is this which shows that using dojo.touch api, manual clicks will trigger both touch and click callbacks, but funcunit clicks will only generate click callbacks


`<html>

<body>
<script type="text/javascript" src="../../../../../test/tools/javascript/libs/funcunit/jquery.js"></script>
<script type="text/javascript" src="../../../../../test/tools/javascript/libs/funcunit/funcunit.js"></script>
<script type="text/javascript" src="../../../../../test/tools/javascript/libs/qunit/qunit.js"></script>
<script type="text/javascript" src="../derived/ui/dojo/dojo.js"></script>

<textarea id="testbox"></textarea>

<script type="text/javascript">
require([
	"dojo/dom",
	"dojo/on",
	"dojo/touch"
	], function (dom, on, touch) {

	var node = dom.byId("testbox");

	on(node, touch.press, function (event) {
		console.log("Touch event registered");
	});

	on(node, "click", function (event) {
		console.log("Click event registered");
	});

	F('#testbox').click();
});

</script>
</body>
</html>`



I will propose it as a topic in an upcoming meeting

**Comment by justinbmeyer** [comment]
Sounds good. We can setup some time to pair on this too.

**Comment by chinmaywanpal** [comment]
Did you folks start working on this? I was also interested in knowing more/ contributing. I came across https://github.com/bitovi/syn/issues/25 from a conversation about pointer events. May be that could be a good place to start about thinking of touch support. What do you think?

**Comment by justinbmeyer** [comment]
@chinmaywanpal yes, syn is where the basic behavior would need to be added first.
