### ISSUE TITLE
Type performs implicit click, why?

### ISSUE THREAD

**Issue by binodpanta** [bitovi/funcunit#136]
Looks like funcunit type method sends a click as part of typing. When applying type to elements like checkboxes, the state of the checkbox can change unexpectedly. Canvas based testing is also weird due to this side effect.

for example

```
F(checkBoxNode).type('[Enter]')
```

causes a click (which causes a toggle), then an Enter which toggles again, which is not the desired result.

Is there any particular reason type includes a click? Can the users be asked to click themselves if they need focus before type?

```
type: function (text, success) { 
            this._addExists(); 
   -------> this.click(); 
            var selector = this.selector; 
            if (text === '') { 
                text = '[ctrl]a[ctrl-up]\b'; 
            } 
            FuncUnit.add({ 
                method: function (success, error) { 
                    syn('_type', this.bind[0], text, success); 
                }, 
                success: success, 
                error: 'Could not type ' + text + ' into ' + this.selector, 
                bind: this, 
                type: 'action' 
            }); 
            return this; 
        },
```

**Comment by justinbmeyer** [comment]
> Is there any particular reason type includes a click? 

An element needs focus so it can be typed on.  A user typically gives an element focus by clicking it or tabbing to it.  I suppose the better fix would be to check if the element has focus, if it doesn't, to then click the element to give it.

**Comment by binodpanta** [comment]
Thanks for the update. My preference would be to have click and type be separate so that users can click then type. Alternatively can you provde a sendkeys which only send keys so that those cases I mentioned can be addressed?

**Comment by binodpanta** [comment]
Any thoughts? Can there be two methods, one that just does a keysend, and another that has the current behavior?

**Comment by justinbmeyer** [comment]
@binodpanta the primary design goal of FuncUnit is to mimic what users do.  An element must be focused before it can receive key events.  That traditionally happens with a click or a `[tab]` so I'm not sure how to enable this with the standard `type` method.

However, I'd be fine exposing a method that just does a keysend if you want to submit a pull request.

**Comment by binodpanta** [comment]
Hi there, we are preparing a change to add a new method F.sendkeys which would be exactly the same usage as type except it won't have the click, we will send a pull request. Is there anything else to the process?

**Comment by matthewp** [comment]
Sounds good!  I think this would probably be a change in syn first? https://github.com/bitovi/syn

syn is what implements type and click and that sort of stuff.

**Comment by binodpanta** [comment]
Thanks @matthewp . I will cameCase the function. 

Would we need a syn change? I was going along the lines of just adding a new method that looks like this in actions.js

```
sendKeys: function( keys, success ) {
    this._addExists();
    var selector = this.selector;
    // type("") is a shortcut for clearing out a text input
    if(keys === ""){
      keys = "[ctrl]a[ctrl-up]\b"
    }
    FuncUnit.add({
      method : function(success, error){
        syn("_type", this.bind[0], keys, success);

      },
      success : success,
      error : "Could not send the keys " + keys + " into " + this.selector,
      bind : this,
      type: "action"
    });
    return this;
  },
```



My current test listed below, is setup to fail if I replace sendKeys() with type(), as it detects any clicks and fails if click was ever registered

QUnit.test("SendKeys without click", function(){
	F.open("test/myapp.html");
	F("#typehereexpectnoclick").sendKeys("javascriptmvc");
	// if this shows up it means that we definitely did not receive a click
	F("#seewhatyoutyped").text("typed javascriptmvc","type still works");
})

**Comment by binodpanta** [comment]
hi there, any thoughts? If not, I will go ahead and submit a pull request

**Comment by binodpanta** [comment]
Hello, I tried to submit my changes into a new branch sendkeys and I get this when I run git push -u origin sendkeys


error: The requested URL returned error: 403 while accessing https://github.com/bitovi/funcunit.git/info/refs

Is there a whitelist of users who can submit? Do I need to get added?

**Comment by matthewp** [comment]
@binodpanta You should be able to fork the repo here: 
<img width="416" alt="screen shot 2016-09-15 at 1 35 54 pm" src="https://cloud.githubusercontent.com/assets/361671/18560393/58b87ebe-7b49-11e6-9e41-dfa85578170d.png">

push your changes to your fork, and then submit a pull request. Thanks!

**Comment by binodpanta** [comment]
oh of course, what am I thinking, got it here

https://github.com/bitovi/funcunit/pull/157

**Comment by binodpanta** [comment]
Any idea if this change can be part of an upcoming release? and whenabouts that release will occur? 

Thanks!

**Comment by justinbmeyer** [comment]
@binodpanta I just merged this.  We'll release it once the new CanJS is out.  Look for it maybe next week.

We're looking for people to help on FuncUnit.  If you're interested in becoming a contributor ... and all the fame and glory that entails, let us/me know (`justin@bitovi.com`).  Thanks!
