### ISSUE TITLE
.exists() isn't counted as an assertion unless a message is defined

### ISSUE THREAD

**Issue by akagomez** [bitovi/funcunit#140]
```
F('selection').exists(); // Expected at least one assertion...
```

```
F('selection').exists('Selection exists'); // 1 assertions of 1 passed, 0 failed.
```

I think the same is true for `.missing()`, though I can't confirm at the moment.

**Comment by matthewp** [comment]
This is definitely true, but it's intentional. It's so you can chain a bunch of stuff and only assert at the end:

```
F('selection').exists().click().doMoreStuff().foo('ok now assert');
```

**Comment by akagomez** [comment]
How would counting the message-less `.exist()` as an assertion prevent you from doing that?

**Comment by matthewp** [comment]
Because FuncUnit works by retrying over and over. So it runs `F('selection').exists()` until it is true, and then goes on to the next thing (`.click()`). it only does assertions when it sees the message.

**Comment by akagomez** [comment]
> ##### Message
>
>The last (optional) parameter for each wait command is a message. By default, wait conditions will pass silently (without a passed assertion).
> If a user provides a message string, the wait condition will pass an assertion with the given message when the wait completes. If the wait fails (the timeout is reached), this message will be provided to the failed assertion.

https://funcunit.com/guides/Guides.waits.html
