### ISSUE TITLE
Tests fail in Travis only

### ISSUE THREAD

**Issue by akagomez** [bitovi/funcunit#145]
I don't have many details. The problem was intermittent originally and I haven't been able to reproduce since I originally worked around the issue here: https://github.com/donejs/bitballs/pull/115. 

At its core, setting `fixture.delay` in one test seemed to indirectly cause failures in other tests. 

I'll follow up with more details as I'm able to identify them. For now this issue serves as a placeholder.

**Comment by matthewp** [comment]
Figure anything out here? If not can we close?

**Comment by mickmcgrath13** [comment]
@akagomez  Can we close this?

**Comment by akagomez** [comment]
Yup. I'm sure I'm remembering incorrectly, but I think that the version of FF that Travis used had some sort of nondeterministic event loop, creating intermittent failures.
