### ISSUE TITLE
[ctrl/alt/cmd/shift]-click support

### ISSUE THREAD

**Issue by jeroencornelissen** [bitovi/funcunit#186]
We would like to have special-key click support to test a multi-select table.
I've tried setting syn's ctrlKey to true and then perform a click, but it doesn't work.

```
syn.key.ctrlKey = true;
F('.table__row:even').click();
```

**Comment by matthewp** [comment]
Can you do something like this? https://github.com/bitovi/syn/blob/master/test/key_test.js#L423

**Comment by kdillon** [comment]
There was a bug in ctrl. It should be fixed in the latest version of Syn
