### ISSUE TITLE
Do not set window.jQuery

### ISSUE THREAD

**Issue by mickmcgrath13** [bitovi/funcunit#187]
The jquery imported calls noConflict which cleans up global `$` and `jQuery`. This file then puts the old version of jQuery back on `window.jQuery`

So if you are using jquery plugins that pass `window.jQuery` into an IIFE you will be using the FuncUnit version of jQuery in the plugin but a newer version in Can (and your tests)

Proposed solution – Remove this line:
https://github.com/bitovi/funcunit/blob/master/browser/init.js#L4
```
window.jQuery = jQuery;
```

**Comment by matthewp** [comment]
LGTM, just need a different entry point for the global build, create a `global.js` that imports FuncUnit's main and then sets window.jQuery = jQuery.

**Comment by jeroencornelissen** [comment]
+1 
We have a simular issue when importing jquery-ui.
