### ISSUE TITLE
dist folder not included on npm

### ISSUE THREAD

**Issue by chasenlehara** [bitovi/funcunit#220]
I just tried republishing but it didn’t include the `dist` folder. Nothing obvious sticks out to me as to why it’s not being published.

**Comment by mckenna** [comment]
I'd love to help with this. Currently blocked from upgrading from v3.0.0 (the last version to include `dist/` in source). The `preversion` script should be run via [the `npm` lifecycle hooks](https://docs.npmjs.com/misc/scripts). 

I don't have a tonne of experience working with `npm`, but I cloned the repository and published  `funcunit` to my own namespace to see what happens. When I published, I noticed that the `preversion` script never ran. Do you have any visibility on whether this script runs for you on publish?

**Comment by chasenlehara** [comment]
Thanks for the help @mckenna, it’s really appreciated!

`preversion`should definitely run; I thought I did when I tried republishing last week.

I’ve been looking at [can-param](https://github.com/canjs/can-param) for reference because it does publish `dist` correctly. [These npm scripts](https://github.com/canjs/can-param/blob/a25aa832c6c0e169bb3deab85a7f0f48384530c2/package.json#L16-L18) look the same to me as what FuncUnit has, but I just noticed that the repo has a [.npmignore](https://github.com/canjs/can-param/blob/a25aa832c6c0e169bb3deab85a7f0f48384530c2/.npmignore) file and this FuncUnit repo doesn’t.

Would you mind adding that file to your test repo and republishing? If it works and you could submit a PR, I can get it merged and released today.

**Comment by mckenna** [comment]
Good call. I added the `.npmignore` file to my test repo and when I deployed it, the `dist/` folder was included. I've submitted a PR to include it.

**Comment by chasenlehara** [comment]
Just published [v3.4.4](https://github.com/bitovi/funcunit/releases/tag/v3.4.4) with your fix. Thank you @mckenna!
