### ISSUE TITLE
Failure while using F.attach(Qunit)

### ISSUE THREAD

**Issue by mgarg1** [bitovi/funcunit#223]
The code below is taken from the QUnit homepage with just 1 addition of funcunit.js 
The failure point is F.attach(QUnit). The error is 

ReferenceError: arugments is not defined
    at Object.<anonymous> (https://rawgit.com/bitovi/funcunit/v3.4.2/dist/funcunit.js:8874:41)

I am looking for a workaround for this as this biting me at many other places.
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>QUnit Example</title>
  <link rel="stylesheet" href="https://code.jquery.com/qunit/qunit-2.6.1.css">
</head>
<body>
  <div id="qunit"></div>
  <div id="qunit-fixture"></div>
  <script src="https://code.jquery.com/qunit/qunit-2.6.1.js"></script>
  <script type="text/javascript" src="https://rawgit.com/bitovi/funcunit/v3.4.2/dist/funcunit.js"></script>

  <script type="text/javascript">
    F.attach(QUnit);
    QUnit.test( "hello test", function( assert ) {
      assert.ok( 1 == "1", "Passed!" );
    });
  </script>
</body>
</html>
```

**Comment by chasenlehara** [comment]
I think this is the line that needs to be updated: https://github.com/bitovi/funcunit/blob/7ec6932b44f2590f30ac98bc091bb43f8f4886ae/browser/adapters/qunit2.js#L17

@mgarg1 Would you be willing to submit a PR that fixes that line?
