### ISSUE TITLE
You can't run getters after actions and waits. Please put your getters in a callback or at the beginning of the test.

### ISSUE THREAD

**Issue by beshoo** [bitovi/funcunit#242]
I am testing funcunit against facebook wall, I include funcunit :
Now when i run 

```
$(document).ready(function() 
{
F("#js_g > div > div > div").visible(function(){
console.log('found');
})
});
```

i got this console error :
**You can't run getters after actions and waits. Please put your getters in a callback or at the beginning of the test.**

please advice

**Comment by chasenlehara** [comment]
That error is thrown here: https://github.com/bitovi/funcunit/blob/f9e31a377de481daa6824ba56c33fd57ceedcfd7/browser/getters.js#L557

FuncUnit is built for running tests for your own site, not simulating actions on another site. I believe the way you’re trying to use it is unsupported.

**Comment by beshoo** [comment]
No that not the case, we are testing on our account...

And i know that the  thrown place, but how to use gater in correct way?
