### ISSUE TITLE
CI setup

### ISSUE THREAD

**Issue by alexisabril** [bitovi/funcunit#53]
_Issue by **[alexisabril](https://github.com/alexisabril)** from Tuesday Sep 03, 2013 at 16:15 GMT_
_Originally opened as https://github.com/bitovi/funcunit.js/issues/8_

----

Currently, travis runs for the master branch on every commit with a successful response(bug in testee).

However, the tests are currently failing when run in phantom.

**Comment by m-mujica** [comment]
Closed by #148.
