### ISSUE TITLE
Question: how to access jQuery for new opened window

### ISSUE THREAD

**Issue by alexisabril** [bitovi/funcunit#57]
_Issue by **[rinatio](https://github.com/rinatio)** from Tuesday Oct 01, 2013 at 18:44 GMT_
_Originally opened as https://github.com/bitovi/funcunit.js/issues/21_
---

Sometimes I'd like to use `jQuery` instead of `F` to execute some code in the "test app window" after `F.open()`. How can I access it? I guess `F.win.$` refers to the app's `jQuery`, not `F.jQuery`, but F.jQuery executes inside `qUnit` window. I know I can use

```
F.jQuery('selector', F.win.document)
```

but is there something simpler? A shortcut?

**Comment by mickmcgrath13** [comment]
Given the age of this latest comment, I'm going to assume that this has been resolved.  If it has not, please re-open.
