### ISSUE TITLE
Publish Func Unit to NPM

### ISSUE THREAD

**Issue by kahnjw** [bitovi/funcunit#76]
Would it be possible to make FuncUnit published on NPM?
---

_Why, you ask?_

Because I have a test suite which runs using browserify, and FuncUnit is shimmed out to work with it. I'm making an installable NPM package that wraps FuncUnit (to make it promise-y) and it will have FuncUnit as a dep.

**Comment by fresheneesz** [comment]
Yes you can, but why not publish it on npm? With Browserify and WebPack, commonJS bundle creation is becoming much more widespread.

**Comment by justinbmeyer** [comment]
Yes, we can do this. Interested in helping?

**Comment by fresheneesz** [comment]
Helping.. publish it on npm? `npm publish` is all you need to do

**Comment by thomblake** [comment]
It's not quite ready.  At least needs a version in package.json, and probably a once-over to make sure it looks sane otherwise.

**Comment by justinbmeyer** [comment]
Yeah, we will probably structure it like: https://github.com/bitovi-components/bit-tabs.  This makes it easy to write in ES6 but export to AMD / CJS / etc.

**Comment by mickmcgrath13** [comment]
https://www.npmjs.com/package/funcunit
