### ISSUE TITLE
Mocha adapter failing tests time out

### ISSUE THREAD

**Issue by daffl** [bitovi/funcunit#80]
Using the Mocha adapters, failing tests do show the error message in the console (as an uncaught error) but officially they time out. This causes `after` hooks not to run and all subsequent tests to fail.

![screen shot 2014-08-07 at 3 24 52 pm](https://cloud.githubusercontent.com/assets/338316/3849460/6c37bfd8-1e79-11e4-92db-ff1c3101f2bf.png)

**Comment by mickmcgrath13** [comment]
Closing this because tests are passing, now.
