### ISSUE TITLE
Clicking button[type=button] shouldn't submit form when clicked

### ISSUE THREAD

**Issue by imjoshdean** [bitovi/funcunit#82]
Ran into this with my client. As it stands, if you have a form that looks something like this:

```
<form>
    <input type="text">
    <button type="submit">Submit</button>
    <button type="button">Does it matter?</button>
</form>
```

And you try simulating a click on the button[type=button] it will submit the form. This is counter to the HTML spec wherein only a button[type=submit] or a button without a type submits a form (more can be read here - http://www.w3.org/TR/html-markup/button.html).

**Comment by mickmcgrath13** [comment]
bitovi/syn#63 Fixed this issue.
