### ISSUE TITLE
FuncUnit not compatible with new StealJS

### ISSUE THREAD

**Issue by asavoy** [bitovi/funcunit#83]
FuncUnit has errors all over the place when trying to use with new StealJS:

* `steal("funcunit/qunit/qunit.css")` needs to be `steal("funcunit/qunit/qunit.css!")`
* `steal.then()` doesn't work
* `steal.bind('ready')` doesn't work
* `steal.config()` throws an error
* some weird ordering of dependencies doesn't seem to work the same way anymore

I've hacked my way through to fix tests for a legacy project, gotten much of the way, but are you guys actually interested in supporting a PR for it? As I'd need help to get it all the way:

* Tests don't seem to be as isolated as they used to (at least I found a test suite that had failing tests, but those tests would pass if run individually)
* It's not backwards compatible with legacy steal - that would be really tricky to do

**Comment by matthewp** [comment]
Will probably start working on this this week.

**Comment by matthewp** [comment]
This is done.
