### ISSUE TITLE
Remove steal conditions

### ISSUE THREAD

**Issue by alexisabril** [bitovi/funcunit#87]
There's a few places where we're tight coupling FuncUnit to StealJS:

```
var fullPath = FuncUnit.getAbsolutePath(path);
```

This breaks in applications that are using new Steal as there is no longer steal.isReady(amongst other API changes).

**Comment by matthewp** [comment]
`getAbsolutePath` doesn't use Steal.  Steal is only used in determining when the page is loaded, but conditionally so it still works without.

**Comment by mickmcgrath13** [comment]
@matthewp @alexisabril Is there still an issue, here?  If not, can we close this issue?

**Comment by matthewp** [comment]
Yeah, fine to close.
