### ISSUE TITLE
FuncUnit seems broken with the very first example

### ISSUE THREAD

**Issue by fresheneesz** [bitovi/funcunit#97]
I downloaded https://raw.githubusercontent.com/bitovi/funcunit/v2.0.4/dist/funcunit.js from the frontpage of the website and tried out the following example in Chrome:

```
<body>
    <div id='a'>a</div>

</body>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script src="FuncUnit.js"></script>

<script>
    $("#a").click(function() {
        console.log("ok")
    })

    F('#a').click();

</script>
```

I get the error: `Uncaught TypeError: Cannot read property 'pauseTest' of undefined  FuncUnit.js:4206 `

I also noticed that there is a *different* link to funcunit.js in the guide ( http://funcunit.com/guides/started.html ), the link being  http://funcunit.com/dist/latest/funcunit.js . I would assume the link there and on the front page should point to the same place - tho it does look like they happen to be the same file right now.

**Comment by justinbmeyer** [comment]
Does FuncUnit work without a test suite like QUnit being in the page?  Where did you get this example from?

cc @alexisabril

**Comment by fresheneesz** [comment]
Ah, I missed the note that QUnit or Jasmine are required. I'm following the get started guide, but didn't expect dependencies to be listed before the bower install instructions.
